name: Build base Docker images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.zephyr
          push: true
          tags: golioth-zephyr-arm:v3.4.0-0.16.1
          build-args: |
            ZEPHYR_VERSION=v3.4.0
            ZEPHYR_SDK_VERSION=0.16.1
            ZEPHYR_SDK_TOOLCHAIN="-t x86_64-zephyr-elf"